### ISSUE TITLE
Warnung BT-82 Zahlungsmittel in UBL nicht erlaubt?

### ISSUE THREAD

**Issue by landrix** [itplr-kosit/validator-configuration-xrechnung#105]
Warum ist BT-82 (InstructionNote) in UBL nicht erlaubt? Laut Spezifikation ja eigentlich schon. CII macht keine Probleme.

`UBL-CR-681 | warning | [UBL-CR-681]-A UBL invoice should not include the PaymentMeans InstructionNote`

```
  <cac:PaymentMeans>
    <cbc:PaymentMeansCode>ZZZ</cbc:PaymentMeansCode>
    <cbc:InstructionNote>https://mypaymentgateway.example.com/resource</cbc:InstructionNote>
    <cbc:PaymentID>Verwendungszweck ...R2020-0815</cbc:PaymentID>
    <cac:PayeeFinancialAccount>
      <cbc:ID>meine@paypaladresse.de</cbc:ID>
      <cbc:Name>Robert Mustermann</cbc:Name>
    </cac:PayeeFinancialAccount>
  </cac:PaymentMeans>
```

In der Visualisierung wird das Zahlungsmittel dann auch nicht angezeigt.

**Comment by phax** [comment]
`BT-82` is bound to `/CreditNote/cac:PaymentMeans/cbc:PaymentMeansCode/@Name` for UBL CreditNote

**Comment by landrix** [comment]
Thanks
