### ISSUE TITLE
[QUESTION] Translation of validation errors

### ISSUE THREAD

**Issue by VLD-UKRAINE** [itplr-kosit/validator-configuration-xrechnung#108]
Hello,
Is it possible to enable translation of validation errors into other languages (besides English), for example, into German?
Thanks.

**Comment by phax** [comment]
Some of the rules provided by the EC are only provided in English and will not be translated - sry

**Comment by VLD-UKRAINE** [comment]
Ok. Thanks for your answer!

**Comment by phax** [comment]
This is a very general issue that hasn't been tackled by the community so far - multilingual validation rules
