### ISSUE TITLE
Generated html report is badly formatted in firefox

### ISSUE THREAD

**Issue by JannickWeisshaupt** [itplr-kosit/validator-configuration-xrechnung#12]
In Firefox the generated report looks like this:

![Screenshot_2019-03-20 Prüfbericht](https://user-images.githubusercontent.com/19517440/54683701-9868a480-4b12-11e9-929e-d3dce1a96094.png)

In Firefox the default font is somewhat larger than in chrome. The css elemet

                .metadata dt {
                float: left;
                width: 230px;
                clear: left;
                }

with the hard coded width is to small to hold the elements: Erkannter Rechnungssteller, Erkannte Rechnungsnummer, Erkanntes Rechnungsdatum. 

Additionally the charset in the html file should be set with:
`<meta` charset="utf-8">

**Comment by rkottmann** [comment]
won't fix the CSS. It is an old fashioned outdated XHTML format and there is `<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />` present. 

Frankly speaking the reports are a bit messy. I tried to achieve to clean it all. This is scheduled for next year. Then we will overhaul the whole report generation. 

If  you have requirements for complete new reports please let us know.

If you want better CSS please help out with mege/pull requests.

In the meantime I will close this issue.
