### ISSUE TITLE
Update configuration to use CEN rules 1.2.2

### ISSUE THREAD

**Issue by rkottmann** [itplr-kosit/validator-configuration-xrechnung#13]
see their release https://github.com/CenPC434/validation/releases/tag/validation-1.2.2

**Comment by phax** [comment]
You are aware, that https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/tag/validation-1.3.1 was already released - right?

**Comment by rkottmann** [comment]
yes, latest configuration release of 2019-12-20 included 1.3.0

next release will include 1.3.1 or newer

**Comment by phax** [comment]
Ah okay. Was just confused because you closed the "use 1.2.2" today :)
