### ISSUE TITLE
Typecode in Example

### ISSUE THREAD

**Issue by jstaerk** [itplr-kosit/validator-configuration-xrechnung#19]
Should the TypeCode in /src/test/instances/cii001.xml not be 380=invoice?

**Comment by rkottmann** [comment]
Thx, for spotting. It is indeed an invalid invoice. However, we actuallz use this invalidity for our tests. It is a negative test example.

**Comment by jstaerk** [comment]
:-) thanks, maybe I should remove it from the list of xrechnung samples on https://mustangproject.org/e-invoices/

**Comment by rkottmann** [comment]
Would be better, I guess.
