### ISSUE TITLE
validation of BR-CL-01 

### ISSUE THREAD

**Issue by grout** [itplr-kosit/validator-configuration-xrechnung#27]
When validating an invoice with one of the construction type codes (875, 876, 877) I get an error when validating a CII-invoice but an information when validating a UBL-invoice.

scenarios.xml contains `<customLevel level="information">BR-CL-01</customLevel>` but only for the UBL rules.

Is this an error or is it not allowed to generate construction invoices using the CII standard?

**Comment by MLatPrefCo** [comment]
Same here, please react.

**Comment by rkottmann** [comment]
Fixed with https://github.com/itplr-kosit/validator-configuration-xrechnung/commit/ef4fdaaceccfa8d498e74ddc03c035b8d1dd982b will be released within the next days (latest beginning of January 2020)
