### ISSUE TITLE
The tempfiles are not used

### ISSUE THREAD

**Issue by christian-schlichtherle** [itplr-kosit/validator-configuration-xrechnung#29]
https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/1e62a804f8c3d049be6b1e5ffc405fdb8891f777/build.xml#L130

**Comment by rkottmann** [comment]
I do not understand what you try to say?

In general tempfile is an ANT concept indicating that the file should be deleted after build process has ended. And that's what I want, becasue they are then not needed anymore.

**Comment by christian-schlichtherle** [comment]
Apparently these temp files are not used at all during the build.
