### ISSUE TITLE
The word `Rechnung` should not occur in the `default-report.xsl`

### ISSUE THREAD

**Issue by christian-schlichtherle** [itplr-kosit/validator-configuration-xrechnung#30]
https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/1e62a804f8c3d049be6b1e5ffc405fdb8891f777/src/default-report.xsl#L774

**Comment by rkottmann** [comment]
Wieso nicht?

**Comment by christian-schlichtherle** [comment]
Weil alle rechnungsspezifischen Ausgaben doch in `xrechnung-report.xsl` vorkommen.

`default-report.xsl` sollte doch generisch sein, oder nicht?

**Comment by christian-schlichtherle** [comment]
> [validator-configuration-xrechnung/src/default-report.xsl](https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/1e62a804f8c3d049be6b1e5ffc405fdb8891f777/src/default-report.xsl#L774)
> Line 774 in [1e62a80](/itplr-kosit/validator-configuration-xrechnung/commit/1e62a804f8c3d049be6b1e5ffc405fdb8891f777)
>  <xsl:text>Inhalt des Rechnungsdokuments:</xsl:text>

Vorschlag: Änderung in "Inhalt des Dokuments:". Informationverlust: null.
