### ISSUE TITLE
Frage zu Validierung

### ISSUE THREAD

**Issue by stedekay** [itplr-kosit/validator-configuration-xrechnung#31]
Hallo, 
ich versuche derzeit Rechnungen aus unserem System als XRechnungen zu verschicken. Ich kenne mich leider noch nicht sehr gut mit dem System aus und weiß deshalb nicht mal, ob ich mit der Frage hier richtig bin:

Ich bekomme beim Validator den folgenden Fehler:
```
Ungültiger Content wurde beginnend mit Element 'cac:PartyLegalEntity' gefunden. 
'{"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":Person, 
"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":AgentParty, 
"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":ServiceProviderParty, 
"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":PowerOfAttorney, 
"urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2":FinancialAccount}' wird erwartet.
```

Der entsprechende Block sieht wie folgt aus:
 ```
<cac:AccountingSupplierParty>
  <cac:Party>
   <cac:PartyName>
    <cbc:Name>Supplier Company Name</cbc:Name>
   </cac:PartyName>
   <cac:PostalAddress>
    <cbc:StreetName>Test</cbc:StreetName>
    <cbc:CityName>Test</cbc:CityName>
    <cbc:PostalZone>12345</cbc:PostalZone>
    <cac:Country>
     <cbc:IdentificationCode>DE</cbc:IdentificationCode>
    </cac:Country>
   </cac:PostalAddress>
   <cac:Contact>
    <cbc:Telephone>030123456</cbc:Telephone>
   </cac:Contact>
   <cac:PartyLegalEntity>
    <cbc:RegistrationName>Supplier Company Name</cbc:RegistrationName>
    <cbc:CompanyID>Company Registration</cbc:CompanyID>
   </cac:PartyLegalEntity>
  </cac:Party>
 </cac:AccountingSupplierParty>
```

Dabei habe ich festgestellt, dass wenn der Contact-Block mit dem PartyLegalEntity-Block vertauscht wird dieser Fehler nicht mehr auftaucht. Spielt die Reihenfolge eine Rolle? Das dürfte doch in einer XML-Datei eigentlich egal sein, oder liege ich hier falsch?

Vielleicht kann mir hier jemand weiterhelfen.

**Comment by landrix** [comment]
Grundsätzlich ist die Reihenfolge natürlich egal. Ich denke mal es liegt an der Art der Validierung und Durchsetzung von Geschäftsregeln, die vielleicht sequentiell erfolgt, da muss man von einer gewissen Reihenfolge der Pflichtfelder ausgehen. So könnte ich es mir erklären.

**Comment by phax** [comment]
Nein, die Reihenfolge der Elemente ist vorgegeben (`xsd:sequence` definiert eine Reihenfolge).
In diesem Fall muss `PartyLegalEntity` vor `Contact` gereiht werden damit es funktioniert.

**Comment by rkottmann** [comment]
thx @phax and the order is determined by the UBL 2.1 Schema.
