### ISSUE TITLE
Question about validating the reports

### ISSUE THREAD

**Issue by christian-schlichtherle** [itplr-kosit/validator-configuration-xrechnung#33]
For our use case we need a machine-readable response to invoice submitters. I am considering to use the generated reports for this purpose. I see there is a schema and even some schematron for the reports, which is great - thanks. I was wondering why the schema doesn't seem to be used however. It should be possible to create another scenario for the reports. I imagine the reason why it's not done is that there would need to be a report for the report? How about the identity transformation?

```xml
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="2.0">
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>  
</xsl:stylesheet>
```

And also there needs to be a way to easily differentiate valid from invalid invoices. I've raised another issue for this.

**Comment by rkottmann** [comment]
Currently, I can not recommend this. We will overhaul the whole report generation process next year. And I am very much tending to use [XVRL](https://github.com/xproc/xvrl) as the machine readable format. This then should work much better for you.

We will also work on other new features as asked by you. If you want to get more details on our plans, please drop me  a line.
