### ISSUE TITLE
[Testsuite] Die eingebetteten Anlage sind in den UBL-Beispielen teilweise unvollständig

### ISSUE THREAD

**Issue by OnlyDex** [itplr-kosit/validator-configuration-xrechnung#34]
In den Beispielen 

- 02.01a-INVOICE_ubl.xml

- 02.02a-INVOICE_ubl.xml

- 03.01a-INVOICE_ubl.xml

- 03.02a-INVOICE_ubl.xml

sind zwar Angaben zu `<cac:AdditionalDocumentReference>` vorhanden, aber die eigentlichen Daten als Binärstrom fehlen. In der jeweiligen uncefact-Variante ist alles korrekt.

**Comment by rkottmann** [comment]
thx for reporting, we working on it

**Comment by rkottmann** [comment]
close, cause resolved quiete a while ago
