### ISSUE TITLE
Surpress warnings: Validation-Warnung UBL-CR-646 A UBL invoice should not include the InvoiceLine SubInvoiceLine

### ISSUE THREAD

**Issue by landrix** [itplr-kosit/validator-configuration-xrechnung#36]
Warum wird diese Warnung ausgegeben? Nach Spezifikation ist das Dokument korrekt.

Sie können das zum Beispiel auch in der mitgelieferten Testsuite des aktuellen Releases mit der Datei 04.02a-INVOICE_ubl.xml nachprüfen.

**Comment by landrix** [comment]
Hi, is german language not welcome?

Why is this warning being given? According to the specification, the document is correct.

You can check this, for example, in the test suite supplied with the current release using the 04.02a-INVOICE_ubl.xml file.

**Comment by rkottmann** [comment]
German language is welcome and English is preferred for the international community.

Your question indicates, that you validated an Extension XRechnung document.

We (XRechnung Schematron Rules) allow SubInvoiceLines. However, the CEN Schematron rules https://github.com/ConnectingEurope/eInvoicing-EN16931/ (not maintained by us, but used in the configuration) disencourage use of SubinvoiceLines . That`s why you get warning from the CEN rules but an all is god from XRechnung Schematron rules.

Depending on your business case etc. you might just disregard the warning.

Does this answer your question?

**Comment by landrix** [comment]
can i suppress this warning for our customers? currently i validate an invoice like this:

java -jar validator\validationtool-1.4.0-java8-standalone.jar -s validator-configuration-200\scenarios.xml -h XRechnung-UBL-200.xml

**Comment by rkottmann** [comment]
No without changing the source code of the report generator, you can not fully supress the warning. In future releases we will add this feature though. But I can give zou no timeline right now
