### ISSUE TITLE
Validation of udt:DateTimeString format

### ISSUE THREAD

**Issue by erdkuk** [itplr-kosit/validator-configuration-xrechnung#37]
Version 1.3.0 of Kosit-Validators with scenario configuration 1.2.2_2019-12-30\scenarios.xml
does not validate the elements "udt:DateTimeString format="102""

According to
https://service.unece.org/trade/untdid/d96a/uncl/uncl2379.htm
format=102 specifies date time format YYYYMMDD.
However, no error is shown in the report if -- for example -- "DDMMYYYY" is used.
I think the validator should output an error if the datetime format is not correct according to the format specifier 102.

**Comment by rkottmann** [comment]
on the one hand it is an issue for https://github.com/ConnectingEurope on the other hand there are inconsistencies in the waz CEN treats dates in the different syntaxes.  IMHO that's why it is of advantage to not be that strict.
