### ISSUE TITLE
validation error [BR-53]-If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.

### ISSUE THREAD

**Issue by landrix** [itplr-kosit/validator-configuration-xrechnung#43]
the attached EN16931 XRechnung (CII) throws a validation error

[BR-53]-If the VAT accounting currency code (BT-6) is present, then the Invoice total VAT amount in accounting currency (BT-111) shall be provided.

but i dont't see an error with this document, all needed information are present

[XRechnung-UNCEFACT.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5580511/XRechnung-UNCEFACT.zip)

```
<ram:InvoiceCurrencyCode>EUR</ram:InvoiceCurrencyCode>
...
<ram:TaxTotalAmount currencyID="EUR">26.00</ram:TaxTotalAmount>

```

**Comment by landrix** [comment]
ok, this tag was to much

`<ram:TaxCurrencyCode>EUR</ram:TaxCurrencyCode>`

**Comment by CFraschak** [comment]
The question is still valid for me, if BT-6 is present in the file it should not result in a problem, even if BT-111 contains the currency code. Can someone explain this behaviour?

**Comment by phax** [comment]
Another source of this error might be, if the version of the EN artefact does not match the XRechnungs validation version
