### ISSUE TITLE
Wrong CustomizationID value for UBL CreditNote Standard Version 2.0.0.

### ISSUE THREAD

**Issue by GregorSz** [itplr-kosit/validator-configuration-xrechnung#46]
Hello!

I wanted to replace the old Xrechnung-Standard 1.2.2. with the newest release: https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/tag/release-2020-07-31

After some analyze I found out that I can't use the new release for Credit Notes because of this validation (file: XRechnung-UBL-validation-CreditNote.xsl):

```
      <xsl:choose>
         <xsl:when test="cbc:CustomizationID = 'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2'"/>
         <xsl:otherwise>
            <svrl:failed-assert xmlns:svrl="http://purl.oclc.org/dsdl/svrl"
                                test="cbc:CustomizationID = 'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2'">
               <xsl:attribute name="id">BR-DE-21</xsl:attribute>
               <xsl:attribute name="flag">warning</xsl:attribute>
               <xsl:attribute name="location">
                  <xsl:apply-templates select="." mode="schematron-select-full-path"/>
               </xsl:attribute>
               <svrl:text>[BR-DE-21] Das Element "Specification identifier" (BT-24) soll syntaktisch der Kennung des Standards XRechnung entsprechen.</svrl:text>
            </svrl:failed-assert>
         </xsl:otherwise>
      </xsl:choose>
```

as you can see the CustomisationID has still the same value as for the Version 1.2.2. In file scenarios.xml we can find the right value for CustomisationID:

```
<match>exists(/creditnote:CreditNote[ cbc:CustomizationID/text() = 'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.0'])</match>
```

So with this state I can't really validate any Credit Note...
I wonder if it is a real bug or maybe the newest release doesn't affect the Credit Note Validations?

Thanks for your help!

**Comment by phax** [comment]
@renzok I can confirm this:
File `UBL/XRechnung-UBL-model.sch`:

```xml
  <param name="BR-DE-21"
    value="cbc:CustomizationID = 'urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_1.2'" />
```

You should add some CreditNote test files ;-)

**Comment by rkottmann** [comment]
If someone has some CreditNote examples, I'd appreciate this.

In general we promote the use of Invoice Syntax with the respective TypeCode, hence CreditNote is a lacking behind in testing.

**Comment by GregorSz** [comment]
Thanks for your fast anwser! 

Here is my example: 
[creditNote.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5651666/creditNote.zip)

**Comment by rkottmann** [comment]
This was fixed in https://github.com/itplr-kosit/xrechnung-schematron/commit/cd1ce874c15f3778a5df664e80dd480047b8a13d#diff-2ba52611dcbdcd4d365d2763f0f5c6e33016ae8434d21626b60da35e5cad0337 and will be added to next release the following days
