### ISSUE TITLE
xrechnung_2.0: Validation failure for invoice type 875 (partial construction invoice)

### ISSUE THREAD

**Issue by griesi007** [itplr-kosit/validator-configuration-xrechnung#47]
The latest release "validator-configuration-xrechnung_2.0.0_2020-07-31" issues a warning in validationtool when validating xrechnung_2.0 and using InvoiceType 875. But this should be accepted. 

"[BR-CL-01]-The document type code MUST be coded by the invoice and credit note related code lists of UNTDID 1001."

[Temp.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5667370/Temp.zip)

**Comment by MLatPrefCo** [comment]
Same here, please react.

**Comment by rkottmann** [comment]
The assesment of the report accepts the invoice although there is a warning from a third party rule (released by CEN). 

We overwrote this failure by customizing the error level https://github.com/itplr-kosit/validator/blob/master/docs/configurations.md

Hence, it is not a failure anymore. The whole validator is about differenatiating technical validation results from recomendation and acceptance see https://github.com/itplr-kosit/validator/blob/master/docs/api.md

**Comment by s137** [comment]
I have almost the same issue, only that in my case it's not a warning but an error and the validator suggests rejection of the invoice, which is a perfectly correct CII XRechnung 2.0 with the typecode 875 from the official referenced codelist UNTDID 1001_2.

I haven't changed any configuration, i just downloaded the Validator and the Validator Config for version 2.0.0 (as mentioned above) as instructed in your wiki.

[XRechnung.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5802465/XRechnung.zip)
