### ISSUE TITLE
xrechnung_2.0: Validation fails when using mulitple InvoiceLine with SubInvoiceLines

### ISSUE THREAD

**Issue by griesi007** [itplr-kosit/validator-configuration-xrechnung#48]
An invoice with multiple invoice lines and at least one invoice line with SubInvoiceLines results in an false positive warning BR-DEX-02. The error does not occur when only one invoice line with SubInvoiceLines is used

Also a warningiUBL-CR-646 is raised that invoice should not include SubInvoiceLine. So far as I understand with "Spezifikation XRechnung Standard und Extension Version XRechnung 2.0.0 | Fassung vom 30.06.2020" SubInvoiceLine should be supported
[Temp.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5674754/Temp.zip)

**Comment by rkottmann** [comment]
thx for reporting. I will have a look into BR-DEX-02.

The warning comes from the CEN rules for NON-Extension. We will not switch them off, however the validotor will still recommend acceptance of XRechnung Extension with Sub Invoice Lines

**Comment by griesi007** [comment]
@rkottmann Regarding BR-DEX-02: So far a I can see this was introduced with the Augut 6th release. For me it looks like a bug not considering that there could be mutiple Invoice line with SubINvoice lines. The amount aggregation works fine when there is only one InvoiceLine with SubInvoiceLines. As soon as there are multiple InvoiceLines with at least on having SubInvoiceLines the validator goes crazy :-)

**Comment by rkottmann** [comment]
As far as I see it, it seems even a bit more tricky. Thx to your example I am getting a grip on it. Stay tuned.

**Comment by rkottmann** [comment]
it is fixed here https://github.com/itplr-kosit/xrechnung-schematron/commit/64e484b8e39ba1185db3b0604f2f19fc7cf1c4d1

will be included in next release of validator configuration the next weeks.

Again thx for reporting. Your eaxample is now inlcuded in our automated tests
