### ISSUE TITLE
Inconsistency in validation of SellerTradeParty/ram:SpecifiedTaxRegistration/ram:ID

### ISSUE THREAD

**Issue by schuetze-Tomislav-Dedus** [itplr-kosit/validator-configuration-xrechnung#5]
There seems to be an inconsistency in the latest release (XRechnung 1.1 on 2018-08-31) in the validation of the Seller VAT Identifier (BT-31) -(SellerTradeParty/ram:SpecifiedTaxRegistration/ram:ID) between the EN16931 and the XRechnung validation files.

The rules BR-CO-26 and BR-S-02  (EN16931) are testing with the schemeID="VAT".
The rule BR-DE-16 (XRechnung) ist testing the Seller VAT Identifier with the schemeID="VA".
In the current validation-scenario you cannot win....
Which one is correct? 

Kind regards,
Tomislav Dedus

**Comment by rkottmann** [comment]
This is a result from inconsitencies in the CEN specification and inconsistent communication of code change in the CEN schematron rules. In their issue https://github.com/CenPC434/validation/issues/57 they moved the fix to the next release but apparently already silentltz published the fix already in the current release...

We are working on a robust solution which makes the xrechnung rule robust against such upstream issues.

**Comment by rkottmann** [comment]
They mentioned the fix but did not close it for their milestone, hence it slipped my attention.

Now fixing issue in https://github.com/itplr-kosit/xrechnung-schematron/issues/12

and closing it here.
