### ISSUE TITLE
Question on test file naming for Validator 1.5.0/XRechnung 2.01 release

### ISSUE THREAD

**Issue by phax** [itplr-kosit/validator-configuration-xrechnung#50]
@rkottmann quick question:
Is there a rule in filenames where I can quickly determine if it is a positive or a negative case?

Currently the following CII test files fail for me:
* cii-br-de-1-test-317-remove.xml
* cii-br-de-10-test-336-remove.xml
* cii-br-de-11-test-287-remove.xml
* cii-br-de-13-invalid-test-bg-17-bg-18-311-identity.xml
* cii-br-de-13-test-bg-17-292-remove.xml
* cii-br-de-13-test-bg-18-303-remove.xml
* cii-br-de-14-test-323-remove.xml
* cii-br-de-15-test-283-remove.xml
* cii-br-de-15-test-285-remove.xml
* cii-br-de-16-negative-tests-br-95-br-151-328-code-Z.xml
* cii-br-de-16-negative-tests-br-95-br-151-329-code-E.xml
* cii-br-de-16-negative-tests-br-95-br-151-330-code-AE.xml
* cii-br-de-16-negative-tests-br-95-br-151-331-code-K.xml
* cii-br-de-16-negative-tests-br-95-br-151-332-code-G.xml
* cii-br-de-16-negative-tests-br-95-br-151-333-code-L.xml
* cii-br-de-16-negative-tests-br-95-br-151-334-code-M.xml
* cii-br-de-16-tests-br-95-br-151-304-code-Z.xml
* cii-br-de-16-tests-br-95-br-151-305-code-E.xml
* cii-br-de-16-tests-br-95-br-151-306-code-AE.xml
* cii-br-de-16-tests-br-95-br-151-307-code-K.xml
* cii-br-de-16-tests-br-95-br-151-308-code-G.xml
* cii-br-de-16-tests-br-95-br-151-309-code-L.xml
* cii-br-de-16-tests-br-95-br-151-310-code-M.xml
* "cii-br-de-17-tests-339-code-326.xml",
* "cii-br-de-17-tests-340-code-380.xml",
* "cii-br-de-17-tests-341-code-384.xml",
* "cii-br-de-17-tests-342-code-389.xml",
* "cii-br-de-17-tests-343-code-381.xml",
* "cii-br-de-17-tests-344-code-875.xml",
* "cii-br-de-17-tests-345-code-876.xml",
* "cii-br-de-17-tests-346-code-877.xml",
* "cii-br-de-17-tests-347-code-383.xml",
* "cii-br-de-17-tests-348-code-527.xml",
* "cii-br-de-18-negative-test-280-identity.xml",
* "cii-br-de-18-negative-test-skonto-290-identity.xml",
* "cii-br-de-18-negative-test2-321-identity.xml",
* "cii-br-de-2-test-315-remove.xml",
* "cii-br-de-22-check-unique-file-name-test-uncefact-325-code-01_15_Anhang_02.pdf.xml",
* "cii-br-de-3-test-289-remove.xml",
* "cii-br-de-4-test-338-remove.xml",
* "cii-br-de-5-test-294-remove.xml",
* "cii-br-de-5-test2-327-remove.xml",
* "cii-br-de-6-test-277-remove.xml",
* "cii-br-de-7-test-313-remove.xml",
* "cii-br-de-8-test-279-remove.xml",
* "cii-br-de-9-test-320-remove.xml"

Please confirm this list is correct.

**Comment by rkottmann** [comment]
many it not all of them should fail. They are generated by the mutator and onlz give correct results with the mutator, because only mutator can test automatically that somethings fails if it also should fail 😄

**Comment by phax** [comment]
Okay, but since they are part of the release package, wouldn't it be good to catgeorize them as "good" and "bad" cases - otherwise it's really hard to guess what's their reason for existance 🤣
