### ISSUE TITLE
Validation error on Typecode 875/877 with XRechnung Version 2.0

### ISSUE THREAD

**Issue by s137** [itplr-kosit/validator-configuration-xrechnung#57]
With your "Validator Configuration release compatible with XRechnung 2.0.0 in version 2020-07-31" I get an error stating that the Typecode is not coded according to the codelist and the validator suggests rejection of the invoice, which should be a correct CII XRechnung 2.0 with the typecode 875 from the official referenced codelist UNTDID 1001_2.

I haven't changed any configuration, i just downloaded the Validator and the Validator Config for version 2.0.0 (as mentioned above) as instructed in your wiki.

With 2.0.1 it is merely a warning, but it still suggests to the invoice recipient that there is some kind of error even if it is accepted. 
But as I see it, the official valid codelist since v1.2.2 should be Revision 2 of UNTDID 1001. Unfortunately many of our customers get their invoices rejected because they have to use these typecodes, considering they work in the construction industry and it is required by law.
 
[XRechnung.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/5819101/XRechnung.zip)

**Comment by GOSTWorker** [comment]
For me, too, this behavior represents an annoying weakness in this validation tool.

**Comment by phax** [comment]
XRechnung code lists rely on the code lists of EN16931, which are in turn subsets of the UNTDID lists.
So for XRechnung to be a CIUS (total subset) of the norm, it cannot accept codes that are not accepted by the EN.

The difference to 2.0.1 is, that this is an "Extension" (a super set, contrary to a CIUS) and as such it can extend code lists.

**Comment by GOSTWorker** [comment]
I do not understand why this list is not compliant with EN16931:
urn:xoev-de:kosit:codeliste:untdid.1001_2
https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:untdid.1001_2#version
https://service.unece.org/trade/untdid/d19b/tred/tred1001.htm

**Comment by rkottmann** [comment]
This should be solved by now. Casue codes are available now.

**Comment by phax** [comment]
This was added in the CEN release 1.3.8 via https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/309
