### ISSUE TITLE
CII val-sch.1.1 BR-51 error msg not clear

### ISSUE THREAD

**Issue by homebeaver** [itplr-kosit/validator-configuration-xrechnung#60]
IST: 

[BR-51]-The last 4 to 6 digits of the Payment card primary account number (BT-87) shall be present if Payment card information (BG-18) is provided in the Invoice.

BESSER wäre:
**Only** the last 4 to 6 digits of ...

Der konkrete Fall:

```xml
            <ram:SpecifiedTradeSettlementPaymentMeans>
                <ram:TypeCode>48</ram:TypeCode>
                <ram:ApplicableTradeSettlementFinancialCard>
                    <ram:ID>****************1234</ram:ID>
                    <ram:CardholderName>Carl Boss</ram:CardholderName>
                </ram:ApplicableTradeSettlementFinancialCard>
            </ram:SpecifiedTradeSettlementPaymentMeans>
```
Nimmt man die Sternchen weg, dann ist die Rechnung vailde!

![grafik](https://user-images.githubusercontent.com/3493126/106339503-0ea1ca80-6297-11eb-8811-9aaa4e5cea3e.png)

![grafik](https://user-images.githubusercontent.com/3493126/106339618-650f0900-6297-11eb-95eb-e7ad0218aef0.png)

regards
EUGen

**Comment by phax** [comment]
Request: change the text of BR-51 from
```
[BR-51]-The last 4 to 6 digits of the Payment card primary account number (BT-87) shall be present if Payment card information (BG-18) is provided in the Invoice.
```
to 
```
[BR-51]-Only the last 4 to 6 digits of the Payment card primary account number (BT-87) shall be present if Payment card information (BG-18) is provided in the Invoice.
```
(Adding the "Only" at the start)

**Comment by phax** [comment]
Handled by https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/267
