### ISSUE TITLE
Namespace change from ubl:Invoice to invoice:Invoice 

### ISSUE THREAD

**Issue by PDesire** [itplr-kosit/validator-configuration-xrechnung#62]
Hey, 

I have a question about the current namespace situation for UBL Invoices:

Depending on line https://github.com/itplr-kosit/validator-configuration-xrechnung/blob/ac36c5066a791178ffa32ac7f0ba86a452859200/scenarios.xml#L47 in your latest release, you changed the namespace from ubl:Invoice to invoice:Invoice. 

I've got some help here: https://github.com/klst-de/e-invoice/issues/20#issuecomment-775177765 where it's still ubl:Invoice.

What I've understood, the ubl:Invoice is the official one for UBL invoices. So why it has been changed for the validator configuration ?

Of course this breaks any validation of any XRechnung XML which is not using invoice:Invoice namespace. 

Thanks !

**Comment by phax** [comment]
You are confusing the "XML namespace URI" and the "XML namespace prefix".
The "prefix" can be arbitrarily chosen, as it is just used as a "placeholder" or "macro". There is no "default UBL namespace prefix"

See e.g. https://en.wikipedia.org/wiki/XML_namespace or https://www.sitepoint.com/xml-namespaces-explained/  for further details.

**Comment by PDesire** [comment]
Oh you are right, thanks for information !
