### ISSUE TITLE
Prüfregeln BR-CO-17 und BR-S-09 schließen sich bei negativen Werten aus

### ISSUE THREAD

**Issue by VoidTenshi** [itplr-kosit/validator-configuration-xrechnung#63]
Bei der Validierung einer XRechnung mit negativen "VAT category taxable amount (BT-116)" kommt es, je nach Rundung, zu einem Fehler durch BR-CO-17 oder BR-S-09. Mit den vorhandenen Werten lässt sich die XRechnung nicht validieren.

Hier die Fehlerberichte:
[error.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/6084492/error.zip)

**Comment by phax** [comment]
May be fixed with https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/256 in release EN 1.3.5.

@VoidTenshi  can you please provide us with a test file? Thank you

**Comment by VoidTenshi** [comment]
[TEST-282674935.txt](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/6350983/TEST-282674935.txt)

Here is a testfile for you.

**Comment by phax** [comment]
Super danke - sorry fürs Englisch ;-)

**Comment by hannibal218bc** [comment]
Würden weitere Testdaten (oder was sonst?) helfen, diesen Fehler zu beheben? Vielen Dank....

**Comment by SunGold70** [comment]
Bei uns besteht mit dem KOSIT 1.4.1 der Fehler leider immer noch 
[BR-CO-17]-VAT category tax amount (BT-117) = VAT category taxable amount (BT-116) x (VAT category rate (BT-119) / 100), rounded to two decimals.
Gibt es eine zusätzliche Regel, die ggf. mit eingebunden werden muss?

**Comment by PatrickVHL** [comment]
@rkottmann it seems this issue has been solved in the new release of XRechnung 2.1.1

Validation in 2.0.0
![image](https://user-images.githubusercontent.com/80406686/144389810-b653e754-6264-4bab-a3f3-19c4506fb57e.png)

Validation in 2.1.1
![image](https://user-images.githubusercontent.com/80406686/144389917-8605a892-d329-42fe-9aef-e45846d06386.png)

**Comment by phax** [comment]
Hey, das sind ja good news :)

**Comment by rkottmann** [comment]
Gut ding will Weile haben. Dann close ich mal mit Happy End 😄
