### ISSUE TITLE
Error in BR-Z-08, trotz korrekter Berechnung

### ISSUE THREAD

**Issue by VoidTenshi** [itplr-kosit/validator-configuration-xrechnung#64]
![pruefbericht](https://user-images.githubusercontent.com/69145399/110614467-a944d180-8192-11eb-8540-08afa61f64a3.png)

Im angehangenen Prüfbericht ist der Wert für "VAT category taxable amount" (BT-116) korrekt berechnet, jedoch wird dieser Wert als fehlerhaft erkannt.

**Comment by phax** [comment]
Seems to be related to https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/254 - fixed in EN 1.3.5.

@VoidTenshi  it would be great, if you could provide us with an example file for this.
