### ISSUE TITLE
[BR-DE-18] Skonto - Nach Update auf validator-configuration-xrechnung_2.0.1_2020-12-31 kaput?

### ISSUE THREAD

**Issue by slue919** [itplr-kosit/validator-configuration-xrechnung#65]
Hallo, 

Nach dem Update auf validator-configuration-xrechnung_2.0.1_2020-12-31 wird folgende Skont-Beschreibnung nicht mehr akzeptiert:

`<ram:SpecifiedTradePaymentTerms>
  <ram:Description>#SKONTO#TAGE=7#PROZENT=2.00#</ram:Description>
</ram:SpecifiedTradePaymentTerms>`

Was könnte das Problem sein.

Vielen Dank.

**Comment by slue919** [comment]
Hier eine Beispiel-Datei

[21_04_16-18_00_XRechnung_2021-00032.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/6326684/21_04_16-18_00_XRechnung_2021-00032.zip)

**Comment by phax** [comment]
Es muss mit einem Newline abgeschlossen sein, dann gehts:
```xml
<ram:SpecifiedTradePaymentTerms> <ram:Description>#SKONTO#TAGE=7#PROZENT=2.00#
</ram:Description> </ram:SpecifiedTradePaymentTerms>
```

das war der Regelteil `matches( rsm:SupplyChainTradeTransaction/ram:ApplicableHeaderTradeSettlement/ram:SpecifiedTradePaymentTerms/ram:Description/text(), '\n\s*$' )` - "Muss mit Newline enden"

**Comment by slue919** [comment]
Vielen Dank. 

So gehts.
