### ISSUE TITLE
validation fail [BR-CO-15] eventhough fields are correct

### ISSUE THREAD

**Issue by kowabungaboy** [itplr-kosit/validator-configuration-xrechnung#68]
Hi,

for an xrechnung validation for a diga product I get the following validation error, both locally and on remote apis when I submit a test-xrechnung

```
val-sch.1.1 | BR-CO-15 | error | [BR-CO-15]-Invoice total amount with VAT (BT-112) = Invoice total amount without VAT (BT-109) + Invoice total VAT amount (BT-110).
Pfad: /ns4:CrossIndustryInvoice/ns4:SupplyChainTradeTransaction[1]/ns2:ApplicableHeaderTradeSettlement[1]/ns2:SpecifiedTradeSettlementHeaderMonetarySummation[1]
```

eventhough the relevant path looks like this:

![image](https://user-images.githubusercontent.com/36469688/128913631-86d8576e-d1bb-4da8-a06f-df2d962afa67.png)

I am using Validator Configuration 2021-07-31 compatible with XRechnung 2.1.1 and KoSIT Validator 1.4.2.

I appreciate any hint to what I am missing.

Thanks in advance and kind regards

**Comment by phax** [comment]
Hi, can you eventually post the message here, or PM it to me (see my profile for my email)?

**Comment by kowabungaboy** [comment]
Hi,

do you mean the following?

![Screenshot from 2021-08-10 20-44-47](https://user-images.githubusercontent.com/36469688/128917661-b948990e-8d22-41cf-94f3-566973fb346d.png)


Let me know if you also want the full xml doc

Thanks and kind regards

**Comment by phax** [comment]
Yes, it would great to have the full XML document - because the Schematron rules are referencing through the document

**Comment by phax** [comment]
Thanks for sending the file by email.
The problem is, that the `ns2:TaxTotalAmount` element is missing the attribute ` currencyID="EUR"`, which (according to BT-110) is mandatory.

**Comment by kowabungaboy** [comment]
Hi, I tried that aswell, but then I get a [CII-DT-031] - currencyID should not be present error. It seems to be the same assertion though? I'll send the files per mail

**Comment by kowabungaboy** [comment]
Hi, my issue was, that both `ns2:TaxTotalAmount` and `ns2:CalculatedAmount` had the attribute currencyID. Only `ns2:TaxTotalAmount` was supposed to have the attribute. Thanks again for your support! I'm closing the issue.
