### ISSUE TITLE
Release 31.07.2021 readme does not fit, download liks are misleadeing

### ISSUE THREAD

**Issue by ubabap** [itplr-kosit/validator-configuration-xrechnung#69]
Hello together,

could you please add all Links, taht are needed for Release 31.07.21 and adapt the readme for this release?  There are 3 Links , whre one is called Code, but does not have code. In the readme is a Link to downlowad version 1.4.1 , but in the text it says, version 1.4.2 is needed... 
Couldn't you just pack everything together in one zip?

**Comment by phax** [comment]
Are you looking for https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/tag/release-2021-07-31 ?

**Comment by ubabap** [comment]
No.  I am asking to improve the information at the mentioned page.

It is not convenient or clear.
I.e.:
There is no link to a validation tool version 1.4.2 and in the actual version of xoev https://www.xoev.de/xrechnung-16828#DL , the bundle to use this year is from 12/20 and it coantins version 1.4.1 .

Also there are 3 Assets
https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/release-2021-07-31/validator-configuration-xrechnung_2.1.1_2021-07-31.zip
https://github.com/itplr-kosit/validator-configuration-xrechnung/archive/refs/tags/release-2021-07-31.zip  (named source code??)
https://github.com/itplr-kosit/validator-configuration-xrechnung/archive/refs/tags/release-2021-07-31.tar.gz  (also name source code)

The first one only contain some style sheets(transformations) etc.. 
Where is the source code for the mentioned version 1.4.2 of the validator itself?   (The future release download on xoev page doen not work, tahe actual contains 1.4.1 )

Could the contained readme.md be adapted to mention the right links according to the changelog and not the old ones?
In the readme .
[README.md](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/7105471/README.md)
the text says 
# download validator
curl -L 'https://github.com/itplr-kosit/validator/releases/download/v1.4.1/validationtool-1.4.1.zip' --output validator.zip

# download configuration
curl -L 'https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/release-2020-12-31/validator-configuration-xrechnung_2.0.1_2020-12-31.zip' --output validator-configuration.zip

# download a test document
curl -L 'https://raw.githubusercontent.com/itplr-kosit/xrechnung-testsuite/master/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml' --output ubl.xml
...

in the changelog:
### Changed

* Using KoSIT Validator v1.4.2
* Using [CEN Schematron Rules 1.3.6a](https://github.com/phax/eInvoicing-EN16931/releases/tag/validation-1.3.6a) from a fork fixing Rule BR-CO-15 
* Using [XRechnung Schematron 1.6.0](https://github.com/itplr-kosit/xrechnung-schematron/releases/tag/release-1.6.0)
* Using [XRechnung Testsuite 2021-07-31](https://github.com/itplr-kosit/xrechnung-testsuite/releases/tag/release-2021-07-31)
* Enhanced `development.md` documentation (thx to phax)



Off topic: i am German and i see mixed langauge issues here.  What is appropriate?

**Comment by ubabap** [comment]
If more are wondering about the incosnistencies in information:
this source [bundle 2.1.1, valid from 1.2.2022](https://www.xoev.de/sixcms/media.php/13/xrechnung-2.1.1-bundle-2021-07-31.zip) ,
does contain the 1.4.2.
According to [xoev download](https://www.xoev.de/xrechnung-16828#DLl) version 2.0.1 has to be used till 31.1.2022.

Here we have some files that are said to be used (or tested?) with 1.4.2 but already for oktober 2021 . 
As it is already september, there is not so much time left to change the setups and maybe implement changes needed.

What is the complete set of files , that needs to be used, now?  
Or very concrete:  can i run the 1.4.1 jar file with the scenarios.xml file of the release mentioned here?  ( does the .jar need more files, that need to be in a certain path structure? Or is all the other stuff in the zip just the source to generate the scenarios.xml file? )

Is it really too hard to just pack everything together in one zip, even if some sources do have other roots?
Or at least provide only the needed links with a clear setup and usage description?

It would be very helpful to provide a: "Run" or "user only" package that only contains the minimal set of files to just run the standard validation without changes(see my questions above).  That might be only the jar and the scenarios.xml  (and a updated readme ) ? 

Best regards

Ulrich Becker

**Comment by bdewein** [comment]
we consider this fixed, please re-open if this is still an issue
