### ISSUE TITLE
Validation error with validator 1.4.2 config 2.1.1

### ISSUE THREAD

**Issue by RytisLT** [itplr-kosit/validator-configuration-xrechnung#70]
When validating an Invoice with `InvoiceTypeCode` `875` using `validator-1.4.2` and `validator-configuration-xrechnung_2.1.1_2021-07-31` the validator reports an error saying that the document does not match the defined standard, yet the `InvoiceTypeCode` `875` is part of the standard.

![image](https://user-images.githubusercontent.com/134529/135107075-9b9dcaee-b445-4c91-a897-086f3b3c0013.png)

**Comment by phax** [comment]
@renzok this one is for you :)

Basically, this is because 875 is not supported in the European Norm

**Comment by rkottmann** [comment]
But it is supported in the XRechnung Extension.

@RytisLT I can't see if you are using the right CustumizationID in the XML Instance. 

It is `urn:cen.eu:en16931:2017#compliant#urn:xoev-
de:kosit:standard:xrechnung_2.1#conformant#urn:xoev-de:kosit:extension:xrechnung_2.1` that you have to use in case of an construction invoice

**Comment by RytisLT** [comment]
@rkottmann The is `CustomizationID` is `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.1#conformant#urn:xoev-de:kosit:extension:xrechnung_2.1`. But the `ProfileID` says `XRechnung 2.0`. Could that be part of the issue?

![image](https://user-images.githubusercontent.com/134529/135219143-51e4f799-7720-44d0-a18e-5b6abf358eec.png)

**Comment by rkottmann** [comment]
hmm `ProfileID` shouldn't be the problem. May I ask you to send the problematic invoice to xrechnung ( a t ) finanzen.bremen.de so that we can have a closer look at the issue?

**Comment by RytisLT** [comment]
@rkottmann the invoice doesn't have any confidential info, so I'll just attach it here

[2021-09-29_1.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/7250857/2021-09-29_1.zip)

**Comment by phax** [comment]
@RytisLT : @renzok  and myself cross checked it, and it only says "information" - so there is no error.

The confusing part is clearly the `(error)` part which originates from the change of the error level. According to the EN that would have been an error, but this one is explicitly allowed in the XRechnung Extension and so 2 error levels are shown, but only `information` is relevant for you. Hence the proposal to "Accept the invoice" (in the grey box)

The problem you identified is "only" in the summary section of the report:
![grafik](https://user-images.githubusercontent.com/196219/135627246-879e8bc2-0244-40a7-9cc0-e063687a6e80.png)

We will take care of this.
