### ISSUE TITLE
[Visualization] CIIs that contain multiple SpecifiedTradeSettlementPaymentMeans with BICs each are not correctly rendered

### ISSUE THREAD

**Issue by JannickWeisshaupt** [itplr-kosit/validator-configuration-xrechnung#71]
In a CII with multiple SpecifiedTradeSettlementPaymentMeans that each contain PayeePartyCreditorFinancialAccount and 
PayeeSpecifiedCreditorFinancialInstitution are rendered with semicolon seperated lists of BICs instead of each iban with its bic.

Here is an example (which is located in CrossIndustryInvoice/SupplyChainTradeTransaction/ApplicableHeaderTradeSettlement):
```     
  <n2:SpecifiedTradeSettlementPaymentMeans>
    <n2:TypeCode>58</n2:TypeCode>
    <n2:PayeePartyCreditorFinancialAccount>
      <n2:IBANID>DEIBAN1</n2:IBANID>
    </n2:PayeePartyCreditorFinancialAccount>
    <n2:PayeeSpecifiedCreditorFinancialInstitution>
      <n2:BICID>BIC1</n2:BICID>
    </n2:PayeeSpecifiedCreditorFinancialInstitution>
  </n2:SpecifiedTradeSettlementPaymentMeans>
  <n2:SpecifiedTradeSettlementPaymentMeans>
    <n2:TypeCode>58</n2:TypeCode>
    <n2:PayeePartyCreditorFinancialAccount>
      <n2:IBANID>DEIBAN2</n2:IBANID>
    </n2:PayeePartyCreditorFinancialAccount>
    <n2:PayeeSpecifiedCreditorFinancialInstitution>
      <n2:BICID>BIC2</n2:BICID>
    </n2:PayeeSpecifiedCreditorFinancialInstitution>
  </n2:SpecifiedTradeSettlementPaymentMeans>
```

Actual Output:
Überweisung

IBAN: DEIBAN1
BIC: BIC1;BIC2

IBAN: DEIBAN2
BIC: BIC1;BIC2

Expected Output:
Überweisung

IBAN: DEIBAN1
BIC: BIC1

IBAN: DEIBAN2
BIC: BIC2

**Comment by bdewein** [comment]
we consider this fixed, if this is still an issue, please re-open
