### ISSUE TITLE
unitCode="KTM" not valid? BR-CL-23

### ISSUE THREAD

**Issue by aronkankel** [itplr-kosit/validator-configuration-xrechnung#72]
If I use unitCode="KTM" für BilledQuantity or BasisQuantity I get BR-CL-23:

[BR-CL-23]-Unit code MUST be coded according to the UN/ECE Recommendation 20 with Rec 21 extension

In UN/ECE are both "KTM" and "KMT" to use for "kilometre".
https://www.xrepository.de/api/xrepository/urn:xoev-de:kosit:codeliste:rec20_2:technischerBestandteilGenericode

Why is "KTM" not supported?

P.S.: https://github.com/ConnectingEurope/eInvoicing-EN16931/blob/master/cii/xslt/EN16931-CII-validation.xslt doesn't cointain "KTM".

**Comment by bdewein** [comment]
we consider this fixed, please reopen, if this is still an issue with the newest version of XRechnung (2.2.0)
