### ISSUE TITLE
[Visualization] High memory consumption of visualization for large invoices

### ISSUE THREAD

**Issue by JannickWeisshaupt** [itplr-kosit/validator-configuration-xrechnung#73]
The visualization files contain a single page-sequence, which contains all content.
This however can lead to very high >2GB memory consumption for large documents with, e.g. many line trade items.
Apache FOP documentation explicitly recommends to use multiple page sequence, see https://xmlgraphics.apache.org/fop/0.95/running.html#memory

For example an invoice with 2000 simple line trade items will lead to a memory consumption of ~500MB.

**Comment by bdewein** [comment]
This issue is handled in GitLab https://projekte.kosit.org/xrechnung/xrechnung-visualization/-/issues/93

**Comment by kosek** [comment]
Is there somewhere available example document with that many lines that could be used for testing?

**Comment by bdewein** [comment]
@JannickWeisshaupt thanks for contributing! We assume that you would be ok if we include this file in our visu codebase. If not, please let us know :)
