### ISSUE TITLE
[Visualization] AdditionalItemProperty (BG-32) is not included in the visualization

### ISSUE THREAD

**Issue by JannickWeisshaupt** [itplr-kosit/validator-configuration-xrechnung#75]
In the visualization files the AdditionalItemProperty field (BG-32) seems to be included, see `detailsPositionArtikeleigenschaften` in `xr-content.xsl`
```  
<xsl:template name="detailsPosition">    
    <xsl:call-template name="detailsPosition_Content"/>    
    <xsl:call-template name="detailsPositionAbrechnungszeitraum"/>
    <xsl:call-template name="detailsPositionPreiseinzelheiten"/>
    <xsl:call-template name="detailsPositionNachlaesse"/>
    <xsl:call-template name="detailsPositionZuschlaege"/>
    <xsl:call-template name="detailsPositionArtikelinformationen"/>
    <xsl:call-template name="detailsPositionArtikeleigenschaften"/>
  </xsl:template>
```
However the field does not actually show up, with e.g. the attached example file
[validUBLeRechnung.zip](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/8529863/validUBLeRechnung.zip)

**Comment by bdewein** [comment]
fixed with xrechnung-visualization 2022-05-31
