### ISSUE TITLE
Kardinalitätsprüfung für BT-17 Tender or lot reference fehlt

### ISSUE THREAD

**Issue by tzcsx** [itplr-kosit/validator-configuration-xrechnung#81]
Gemäß der Spezifikation hat BT-17 die Kardinalität 0..1, jedoch wird dies nicht vom Validator geprüft.
[invoice_cefact_2.3.xml.txt](https://github.com/itplr-kosit/validator-configuration-xrechnung/files/12013015/invoice_cefact_2.3.xml.txt) ist eine CEFACT Rechnung, die laut XRechnung Validatorkonfiguration gültig ist, jedoch kein gültiges semantisch Modell abbildet, da zwei BT-17 Instanzen enthalten sind:
```
<ram:AdditionalReferencedDocument>
	<ram:IssuerAssignedID><![CDATA[12345A1]]></ram:IssuerAssignedID>
	<ram:TypeCode>50</ram:TypeCode>
</ram:AdditionalReferencedDocument>
<ram:AdditionalReferencedDocument>
	<ram:IssuerAssignedID><![CDATA[67890B2]]></ram:IssuerAssignedID>
	<ram:TypeCode>50</ram:TypeCode>
</ram:AdditionalReferencedDocument>
```

**Comment by bdewein** [comment]
Die Prüfung der Kardinalität von BT-17 wurde als Prüfregel CII-SR-457 mit der Version 1.3.11 in die CEN-Validierungsartefakte  aufgenommen (s. https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/353). Diese sind wiederum Bestandteil des aktuellsten Releases der Validator Konfiguration XRechnung  (2023-11-15).
