### ISSUE TITLE
Upload xrechnung for xrepository

### ISSUE THREAD

**Issue by razilein** [itplr-kosit/validator-configuration-xrechnung#82]
Hello,

xrechnung could not be found at https://www.xrepository.de/. Only some codelists are available.
Can you please upload all versions?

At https://xeinkauf.de/dokumente/ there is only version 3.0.0 available for download.
This is enough for my purpose, but all versions should be still available at xrepository.

**Comment by rkottmann** [comment]
Hi,

it is a bit hidden in the navigation. However, here you will find all versions https://xeinkauf.de/xrechnung/versionen-und-bundles/ .

Hope this helps. If you have more such feedbackplease sent Email to xeinkauf@finanzen.bremen.de

Bests,

renzo
