### ISSUE TITLE
Currency Code check not compliant to spec

### ISSUE THREAD

**Issue by SteinRobert** [itplr-kosit/validator-configuration-xrechnung#83]
I just checked the code list (Anhang B) for XRechnung 2.3.1 (https://xeinkauf.de/app/uploads/2023/02/231-XRechnung-2023-02-03.pdf).
It says for currency codes this one is used:
https://www.xrepository.de/details/urn:xoev-de:kosit:codeliste:currency-codes_3

I tried to validate documents with these currency codes (which should be present in version 3 of the code list):
 - `STN`
 - `VES`
 - `MRU`
 - `UYW`
 
 The validation of either fails.
 I'm using the scenarios from this release (2.3.1):
 https://github.com/itplr-kosit/validator-configuration-xrechnung/releases/download/release-2023-05-12/validator-configuration-xrechnung_2.3.1_2023-05-12.zip
 For the validator I use version 1.5.0
 https://github.com/itplr-kosit/validator/releases/download/v1.5.0/validator-1.5.0-distribution.zip
 
 Am I overlooking something? Why is the document rejected?
 ![Bildschirmfoto 2023-08-15 um 17 52 59](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/1231105/f19e4531-20b7-4d95-bc3d-d7c7d811f135)

**Comment by SteinRobert** [comment]
@bdewein do you have any idea what the problem is?

**Comment by bdewein** [comment]
@SteinRobert thanks for reporting!

Codelist values are validated by CEN validation artefacts, which are integrated into the XRechnung artefacts. The codes you mentioned are currently not included in the respective codelists. We filed an issue at https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/356. 

On a general note: Appendix B in the XRechnung Specification PDF is purely informative as codelists are published by different organizations and are subject to release cycles independent of XRechnung's, which can cause overlaps/delays in implementation.

**Comment by SteinRobert** [comment]
Thanks for clearing this up! We stumbled across this implementing tests for our XRechnung generation. We'll exclude these currencies from our tests for now then.
