### ISSUE TITLE
Different warrning/error when using CII or UBL

### ISSUE THREAD

**Issue by j-stefke** [itplr-kosit/validator-configuration-xrechnung#85]
Hello,

when using the validator with die actual Validator Configuration from 2023-11-15 we receive in UBL for example for Codes PEPPOL-EN16931-R020, PEPPOL-EN16931-R010 an error, when validating the CII XML we receive only a warning. Why do we receive for CII only a warrning? It seems that all new processrules with PEPPOL-EN16931-RXXX shown in CII as warrning instead of error. Is there a reason why? The next Problem i see with the warrnings - that the messages could be forward without this relevant informations ("Bewertung: Es wird empfohlen das Dokument anzunehmen und weiter zu verarbeiten.") And just one more question for what is the code CII-SR-453 in the report itself ? 

UBL: 
![image](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/155972776/49defdbd-4eb3-4cb1-8d02-119bcf4fcdd0)

CII: 
![image](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/155972776/6b3a57b4-56cd-41a2-be8f-ce848213ab9e)

301 Xrechnung documentation:
![image](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/155972776/264dd9a9-4baf-4bd0-b3ef-3b30c9dda009)
![image](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/155972776/ba119266-55e5-4286-97c6-b0b73b251122)

Thanks an kind regards

**Comment by bdewein** [comment]
As Peppol BIS Billing 3.0 does not officially support CII, in XRechnung 3.0 all new PEPPOL-EN16931-xxx rules were set to "warning" in CII for a transitional period (see chapter 13.4 in the Specification XRechnung).

`CII-SR-453` was added with CEN Schematron version 1.3.11 (implemented with the latest release of validator-configuration-xrechnung) to ensure BT-20 (Payment terms) cardinality of `0..1` in CII.

**Comment by svanteschubert** [comment]
Dear KoSIT team,

Shouldn't business rules be independent of syntax? 
In natural language, shouldn't a sentence be "TRUE / FALSE" regardless of whether I say the sentence in French or English?
Can we guarantee that no Peppol provider or ZRE/OZG-RE will use a CII2UBL transformation first and validate afterwards?
In this case, a valid CII invoice at the sender becomes an invalid UBL invoice at the recipient! I fear that this is likely to be the case and will cause a lot of frustration and cost in the community.
We should not take this risk!
Therefore, I strongly suggest aligning the validation levels of both syntaxes to keep them harmonized!

Kind regards,
Svante

PS: 
Why do you believe CII is not officially supported by Peppol? 
It is an official Peppoll document type: 
![image001 (4)](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/825051/0eac7412-8816-42bb-9010-9bf9e52e38d5)
from 
https://docs.peppol.eu/edelivery/codelists/v8.7/Peppol%20Code%20Lists%20-%20Document%20types%20v8.7.html

**Comment by phax** [comment]
@svanteschubert  there is a differentiation between "Peppol" and "XRechnung on Peppol".
* Peppol does everything in UBL and the Peppol BIS Billing is only fully defined in UBL. To be compliant to the norm we allow sending plain CII document via Peppol, but they are not "Peppol BIS Billing" but plain "EN CII" documents. That's what @bdewein  was referring to
* XRechnung on Peppol does support UBL Invoice, UBL CreditNote and CII for all versions over Peppol.

**Comment by tobitege** [comment]
> As Peppol BIS Billing 3.0 does not officially support CII, in XRechnung 3.0 all new PEPPOL-EN16931-xxx rules were set to "warning" in CII for a transitional period (see chapter 13.4 in the Specification XRechnung).

Does that mean that middle- to longterm Xrechnung has to be PEPPOL-compliant, no matter whether customers actually use PEPPOL?
I hope any change of warnings to fatal will be communicated WAY in advance for use software developers. :)
