### ISSUE TITLE
"Seller Name" and "Seller Trading Name" swappped between nodes in some testinvoices of your testsuite

### ISSUE THREAD

**Issue by KaeseToBa** [itplr-kosit/validator-configuration-xrechnung#87]
When using your test suite, we noticed that in the test invoices in UBL format starting with "02." in the file name, the contents "Seller Name" and "Seller Trading Name" were swapped between their nodes compared to the test invoices starting with "01.".

This refers to the nodes "PartyTaxScheme.PartyLegalEntity.RegistrationName" and "Party.PartyIdentification.PartyName.Name". 

Only invoices in UBL format are affected. It is not swapped in invoices in UNCEFACT format. Therefore we think that it could be a bug in the testsuite. 

##### 01.01a-INVOICE_ubl.xml
https://github.com/itplr-kosit/xrechnung-testsuite/blob/6a9927df07d7f5ea951bff8d084bddcec7df55d2/src/test/business-cases/standard/01.01a-INVOICE_ubl.xml#L17
![image](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/8308113/5b2e94de-ed34-45e0-9105-28a8898e2f2a)

##### 02.01a-INVOICE_ubl.xml
https://github.com/itplr-kosit/xrechnung-testsuite/blob/6a9927df07d7f5ea951bff8d084bddcec7df55d2/src/test/business-cases/standard/02.01a-INVOICE_ubl.xml#L45
![image](https://github.com/itplr-kosit/validator-configuration-xrechnung/assets/8308113/0225950d-97d8-46cb-88b4-ac85e02606b5)

best regards

**Comment by lkumai** [comment]
Thank you for your contribution! We will check this.
Kind regards

**Comment by lkumai** [comment]
We have fixed this in this commit: https://github.com/itplr-kosit/xrechnung-testsuite/commit/fb841cf0b378977829d5aae33f4d09a9c72856d7
Thank you again @KaeseToBa
