### ISSUE TITLE
src/test/instances/ubl003.xml ist nicht valide

### ISSUE THREAD

**Issue by homebeaver** [itplr-kosit/validator-configuration-xrechnung#9]
denn seller country code wurde auskommentiert.

Das ergibt

Referenz:
    ubl003.xml
Zeitpunkt der Prüfung:
    28.5.2019 17:49:14
Erkannter Dokumenttyp:
    EN16931 CIUS XRechnung (UBL Invoice)

Erkannter Rechnungssteller:
    De Koksmaat
Erkannte Rechnungsnummer:
    12115118
Erkanntes Rechnungsdatum:
    2015-01-09

Konformitätsprüfung: Das geprüfte Dokument enthält 1 Fehler / 0 Warnungen. Es ist nicht konform zu den formalen Vorgaben. 

Pos | Code | Adj. Grad (Grad) | Text
-- | -- | -- | --
val-sch.1.1 | BR-09 | error | [BR-09]-The Seller postal address (BG-5) shall contain a Seller country code (BT-40).
Pfad: /Invoice/cac:AccountingSupplierParty[1]/cac:Party[1]/cac:PostalAddress[1]

**Comment by rkottmann** [comment]
it it should not be, it is a negative test to check that we report errors correctly
