### ISSUE TITLE
PEPPOL-EN16931-R001 Business process MUST be provided. AND [BR-DE-21] "Specification identifier" (BT-24) 

### ISSUE THREAD

**Issue by Zero-create1** [itplr-kosit/validator-configuration-xrechnung#93]
Hello,
I'm trying to recreate the warning that I have on other validation sites, but they don't appear. 

I get this warning on a site that also uses Kosit:
![Screenshot 2024-08-08 141617](https://github.com/user-attachments/assets/e55bfa0f-7f63-4f79-9040-461ecbf603ae)

But I don't get a warning when validating the same file in CLI with "validationtool-1.5.0-standalone.jar" and "validator-configuration-xrechnung_3.0.2_2024-06-20".

Please help.

**Comment by Zero-create1** [comment]
Hello @bdewein,
for example, when validating ErrorTest.xml I get the report that everything is fine:

![Screenshot 2024-08-12 115105 - Kopie](https://github.com/user-attachments/assets/3209e1b6-3fb2-46c7-aa47-ebef893e9366)

But when validating it on https://erechnungsvalidator.service-bw.de/ I get 8 warnings and 1 error.
I can't upload XML Files so here is the txt:

[ErrorTest.txt](https://github.com/user-attachments/files/16580061/ErrorTest.txt)

**Comment by phax** [comment]
@Zero-create1  short site note: the validator you mentioned uses XRechnung 3.0.1 configuration:
> Validator Konfiguration für XRechnung 3.0.1 für die Universal Business Language (UBL) und UN/CEFACT Invoice und CreditNote Dokumente mit EN16931:2017, genauer:
That might also be an issue...

**Comment by bdewein** [comment]
Thanks @phax for clarifying.

@Zero-create1 by using `urn:cen.eu:en16931:2017` as the specification identifier (BT-24) in your example invoice, you are declaring conformity with the EN 16931 (not with XRechnung, which is based on the EN 16931) and the validator-configuration-xrechnung is validating against CEN Schematron rules, only, disregarding XRechnung Schematron rules. Exchange the specification identifier with `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0` and the validation scenario for CIUS XRechnung will be used, resulting in BR-DE-2 error and several warnings on PEPPOL-EN16931-rules (please note that the severity level of these rules will be raised to error, soon).

**Comment by Zero-create1** [comment]
Hi, it actually works then, thank you both very much. ☻
I didn't quite understand what the difference between CEN Schematron and XRechnung Schematron is. 
But can I then configure the validator in a way, that it always looks at the XRechnung Schematron rules?
So that even if my document doesn't have the identifier `#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0`, it will still tell me that the identifier is missing and show the other errors/warnings as well?

**Comment by Laob** [comment]
Hi @Zero-create1,
theoretically you can edit the scenarios.xml, so it will use the XRechnung rules instead of the CEN rules. You have to remove the CEN scenarios (for CII ll. 434) and have to edit the match of the XRechnung scenarios (for CII l. 233), but I think it would be much better to use the XRechnung specification identifier instead.

**Comment by lkumai** [comment]
Hi @Zero-create1,
theoretically you can edit the scenarios.xml, so it will use the XRechnung rules instead of the CEN rules. You have to remove the CEN scenarios (for CII ll. 434) and have to edit the match of the XRechnung scenarios (for CII l. 233), but I think it would be much better to use the XRechnung specification identifier instead.

**Comment by Zero-create1** [comment]
Hi,
thank you all for your help. My main problem has been fixed. 
I will close the issue.
Thanks again. ☻
