### ISSUE TITLE
Fehlender Error Text

### ISSUE THREAD

**Issue by SemikolonDEV** [itplr-kosit/validator-configuration-xrechnung#94]
Die Peppol Warnung `PEPPOL-EN16931-R040`  hat keinen Fehlertext.

![image](https://github.com/user-attachments/assets/b709f4d2-0928-4a59-9e97-313d7ffaa08d)

In der XSL für XRechung-UBL ist nur ein Empty Tag:
![image](https://github.com/user-attachments/assets/49a8fdfb-36a7-422b-adf7-f4c02b70111a)
In der XSL für CII ebenfalls:
![image](https://github.com/user-attachments/assets/5fb524f3-b38e-49f0-b7c2-952be503cb97)

**Comment by SemikolonDEV** [comment]
https://github.com/itplr-kosit/validator-configuration-bis/blob/b62701b2de498a86c2fe2f39613bfcf2c20d7f49/resources/peppol/billing-bis/3.0.16/PEPPOL-EN16931-UBL.xslt#L633C22-L633C122

**Comment by lkumai** [comment]
Vielen Dank für die Meldung. Diese wird bereits hier bearbeitet: https://github.com/itplr-kosit/validator-configuration-xrechnung/issues/92
