### ISSUE TITLE
UBL Gutschrift 381 nicht mehr möglich?

### ISSUE THREAD

**Issue by landrix** [itplr-kosit/validator-configuration-xrechnung#95]
Hallo,

neuerdings erhalte ich bei der Validierung von UBL-Gutschriften mit dem InvoiceTypeCode 381 die Meldung

[BR-CL-01]-The document type code MUST be coded by the invoice and credit note related code lists of UNTDID 1001.
Pfad: /ubl:Invoice/cbc:InvoiceTypeCode[1]

Auch in dieser Liste ist der Code nicht mehr enthalten:

https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-inv/

Was ist hier passiert? Im CII-Format funktioniert alles.
[Gutschrift.txt](https://github.com/user-attachments/files/16940250/Gutschrift.txt)

**Comment by phax** [comment]
Für XRechnung 3.0.2 nehme ich an?

**Comment by landrix** [comment]
Sowohl 3.0.2 als auch 2.3.1

**Comment by msccip** [comment]
Die Tags und Namespaces für UBL Gutschriften (381) heißen "CreditNote" nicht "Invoice"

**Comment by msccip** [comment]
s. https://docs.peppol.eu/poacc/billing/3.0/codelist/UNCL1001-cn/

**Comment by landrix** [comment]
OK, war mir gar nicht so bewusst. Und kann ich CreditNote mit dem Validator prüfen? Da kommt dann nämlich

Bewertung: Es wird empfohlen das Dokument zurückzuweisen. Da kein Pruefszenario gegriffen hat.

**Comment by msccip** [comment]
Das liegt an der   <cbc:CustomizationID>urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0</cbc:CustomizationID>

für Gutschriften gibt es keine "extension"

**Comment by landrix** [comment]
ok, da hat sich das Thema ja erst mal erledigt. Muss man eben CII nehmen.

**Comment by msccip** [comment]
solange man keine Unterpositionen (SubInvoiceLine) verwendet, muss man ja kein extended benutzen ...

**Comment by phax** [comment]
Achtung: die UBL `CustomizationID` hat sich zwischen 2.x und 3.x verändert (`xoev.de` or so wurde zu `xeinkauf.de`)!
Ansonsten bietet die Default-Konfiguration aber alle notwendigen Regeln mit.

Hier die möglichen Customization IDs für 2.3:
* UBL Invoice: `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3`
* UBL CreditNote: `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3`
* CII: `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3`
* UBL Invoice Extension: `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3#conformant#urn:xoev-de:kosit:extension:xrechnung_2.3`
* UBL CreditNote Extension: `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3#conformant#urn:xoev-de:kosit:extension:xrechnung_2.3`
* CII Extension: `urn:cen.eu:en16931:2017#compliant#urn:xoev-de:kosit:standard:xrechnung_2.3#conformant#urn:xoev-de:kosit:extension:xrechnung_2.3`

Hier die möglichen Customization IDs für 3.0:
* UBL Invoice: `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0`
* UBL CreditNote: `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0`
* CII: `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0`
* UBL Invoice Extension: `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0`
* UBL CreditNote Extension: `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0`
* CII Extension: `urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0`

hth

**Comment by msccip** [comment]
Sorry, es gibt keine UBL CreditNote Extension. Aktuelle scenarios.xml (3.0.2):

<?xml version="1.0" encoding="UTF-8"?>
<!-- This is the source file for creating scenarios.xml 
  -
  - DO NOT USE DIRECTLY
  -->
<scenarios xmlns="http://www.xoev.de/de/validator/framework/1/scenarios"
  frameworkVersion="1.0.0">
  <name>Validator Configuration XRechnung 3.0.2</name>
  <author>Coordination Office for IT Standards (KoSIT)</author>
  <date>2024-06-20</date>
  <description>
    <p>Checks whether XML Documents conform to XRechnung specification
            3.0.2
            (https://xeinkauf.de/xrechnung/versionen-und-bundles/).</p>
    <p>It uses CEN Schematron rules of urn:cen.eu:en16931:2017
            in version 1.3.12 from 2024-06-20
            (https://github.com/ConnectingEurope/eInvoicing-EN16931/releases).</p>
    <p>It uses Schematron Rules version 2.1.0 for XRechnung specification version
            3.0.2 
            (https://github.com/itplr-kosit/xrechnung-schematron/releases/download/release-2.1.0/xrechnung-3.0.2-schematron-2.1.0.zip).</p>
  </description>

  <!-- XRECHNUNG specific scenarios -->
  <!-- XRECHNUNG Standard (CIUS) UBL Invoice -->
  <scenario>
    <name>EN16931 XRechnung (UBL Invoice)</name>
    <description>
      <p>Validates UBL Invoice in version 2.1</p>
      <p>Uses UBL Invoice 2.1 XML Schema,
                Schematron rules from EN16931:2017, and XRechnung
                3.0.2 </p>
      <p>Download of UBL XML Schema on 2024-06-20 from
                http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.zip</p>
      <p>Download of UBL Schematron rules on 2024-06-20 from
                https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-ubl-1.3.12.zip</p>
      <p>Download of XRechnung Schematron rules on 2024-06-20 from
                https://github.com/itplr-kosit/xrechnung-schematron/releases/download/release-2.1.0/xrechnung-3.0.2-schematron-2.1.0.zip</p>
    </description>
    <!-- UBL Invoice namespaces -->
    <namespace prefix="cbc"
      >urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2</namespace>
    <namespace prefix="invoice"
      >urn:oasis:names:specification:ubl:schema:xsd:Invoice-2</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>

    <match>exists(/invoice:Invoice/cbc:CustomizationID[ . = 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0']) </match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UBL 2.1 Invoice</name>
        <location>resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (UBL)</name>
        <location>resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for Invoice - CIUS XRechnung (UBL)</name>
        <location>resources/xrechnung/3.0.2/xsl/XRechnung-UBL-validation.xsl</location>
      </resource>

    </validateWithSchematron>
    <createReport>
      <resource>
        <name>Validation report for XRechnung</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
      <!-- custom level "information" for BR-CL-01 was removed as construction codes were added to Codelist 1001 with CEN 1.3.8 (see CEN issue https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/309) --> 
      <!-- overwrites CEN severity level "fatal" for codelist values of BT-130 "Invoiced quantity unit of measure code" and BT-150 "Item price base quantity unit of measure code" -->
      <customLevel level="warning">BR-CL-23</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-157 "Item standard identifier" scheme identifier -->
      <customLevel level="warning">BR-CL-21</customLevel>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>
  
  <!-- XRECHNUNG Extension UBL Invoice -->
  
  <scenario>
    <name>EN16931 XRechnung Extension (UBL Invoice)</name>
    <description>
      <p>Validates UBL Invoice in version 2.1</p>
      <p>Uses UBL Invoice 2.1 XML Schema,
        Schematron rules from EN16931:2017, and XRechnung
        3.0.2 </p>
      <p>Download of UBL XML Schema on 2024-06-20 from
        http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.zip</p>
      <p>Download of UBL Schematron rules on 2024-06-20 from
        https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-ubl-1.3.12.zip</p>
      <p>Download of XRechnung Schematron rules on 2024-06-20 from
        https://github.com/itplr-kosit/xrechnung-schematron/releases/download/release-2.1.0/xrechnung-3.0.2-schematron-2.1.0.zip</p>
    </description>
    <!-- UBL Invoice namespaces -->
    <namespace prefix="cbc"
      >urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2</namespace>
    <namespace prefix="invoice"
      >urn:oasis:names:specification:ubl:schema:xsd:Invoice-2</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>
    
    <match>exists(/invoice:Invoice/cbc:CustomizationID[ . = 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0'])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UBL 2.1 Invoice</name>
        <location>resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (UBL)</name>
        <location>resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for Invoice - XRechnung (UBL)</name>
        <location>resources/xrechnung/3.0.2/xsl/XRechnung-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <createReport>
      <resource>
        <name>Validation report for XRechnung</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
      <!-- custom level "information" for BR-CL-01 was removed as construction codes were added to Codelist 1001 with CEN 1.3.8 (see CEN issue https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/309) --> 
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-157 "Item standard identifier" scheme identifier and to enable DIGA codes (BR-DEX-06) -->
      <customLevel level="information">BR-CL-21</customLevel>
      <!-- overwrites CEN severity level "fatal" for codelist values of BT-130 "Invoiced quantity unit of measure code" and BT-150 "Item price base quantity unit of measure code" -->
      <customLevel level="warning">BR-CL-23</customLevel>
      <!-- overwrites CEN severity level "fatal" to enable use of mime codes defined per BR-DEX-01 -->
      <customLevel level="warning">BR-CL-24</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-29, BT-46, and BT-60 scheme identifiers to enable DIGA codes (BR-DEX-04) -->
      <customLevel level="information">BR-CL-10</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-30, BT-47, and BT-61 scheme identifiers to enable DIGA codes (BR-DEX-05) -->
      <customLevel level="information">BR-CL-11</customLevel>
      <!-- overwrites CEN severity level "fatal" for CEF EAS values of BT-34 and BT-49 scheme identifiers to enable DIGA codes (BR-DEX-07) -->
      <customLevel level="information">BR-CL-25</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-71 scheme identifier to enable DIGA codes (BR-DEX-08) -->
      <customLevel level="information">BR-CL-26</customLevel>
      <!-- overwrites CEN severity level "fatal" to enable Third Party Payment calculations (BR-DEX-09) -->
      <customLevel level="information">BR-CO-16</customLevel>
      <!-- overwrites CEN severity level "warning" for implementation of Third Party Payment (BG-DEX-09) -->
      <customLevel level="information">UBL-CR-470</customLevel>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>
  
  
  <scenario>
    <name>EN16931 XRechnung (UBL CreditNote)</name>
    <description>
      <p>Validates UBL CrediteNote version 2.1</p>
      <p>Uses UBL CreditNote 2.1 XML Schema, 
                Schematron rules from EN16931:2017, and XRechnung
                3.0.2 </p>
      <p>Download of UBL XML Schema on 2024-06-20 from
                http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.zip</p>
      <p>Download of UBL Schematron rules on 2024-06-20 from
                https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-ubl-1.3.12.zip</p>
      <p>Download of XRechnung Schematron rules on 2024-06-20 from
                https://github.com/itplr-kosit/xrechnung-schematron/releases/download/release-2.1.0/xrechnung-3.0.2-schematron-2.1.0.zip</p>
    </description>
    <!-- UBL CrediteNote Namespaces -->
    <namespace prefix="cbc"
      >urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2</namespace>
    <namespace prefix="creditnote"
      >urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>

    <match>exists(/creditnote:CreditNote[ cbc:CustomizationID/text() = 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0'])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UBL 2.1 CreditNote</name>
        <location>resources/ubl/2.1/xsd/maindoc/UBL-CreditNote-2.1.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (UBL)</name>
        <location>resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for CreditNote - CIUS XRechnung (UBL)</name>
        <location>resources/xrechnung/3.0.2/xsl/XRechnung-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <createReport>
      <resource>
        <name>Validation report for XRechnung</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
      <!-- custom level "information" for BR-CL-01 was removed as construction codes were added to Codelist 1001 with CEN 1.3.8 (see CEN issue https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/309) --> 
      <!-- overwrites CEN severity level "fatal" for codelist values of BT-130 "Invoiced quantity unit of measure code" and BT-150 "Item price base quantity unit of measure code" -->
      <customLevel level="warning">BR-CL-23</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-157 "Item standard identifier" scheme identifier -->
      <customLevel level="warning">BR-CL-21</customLevel>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>
  
  <!-- XRechnung Standard (CIUS) CII -->
  
  <scenario>
    <name>EN16931 XRechnung (CII)</name>
    <description>
      <p>Validates UN/CEFACT XML (SCRDM - CII uncoupled) version
                D16B</p>
      <p>Uses UN/CEFACT (SCRDM - CII uncoupled) version
                D16B XML Schema, Schematron rules from EN16931:2017,
                and XRechnung Schematron rules version 3.0.2 </p>
      <p>Download of CII uncoupled XML Schema on 2024-06-20 from
                http://www.unece.org/fileadmin/DAM/cefact/xml_schemas/D16B_SCRDM__Subset__CII.zip</p>
      <p>Download of CII Schematron rules on 2024-06-20 from
                https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-cii-1.3.12.zip </p>
      <p>Download of XRechnung Schematron rules on 2024-06-20 from
                https://github.com/itplr-kosit/xrechnung-schematron/releases/download/release-2.1.0/xrechnung-3.0.2-schematron-2.1.0.zip</p>
    </description>
    <!-- CII namespaces -->
    <namespace prefix="rsm"
      >urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100</namespace>
    <namespace prefix="ram"
      >urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>

    <match>exists(/rsm:CrossIndustryInvoice[rsm:ExchangedDocumentContext/ram:GuidelineSpecifiedDocumentContextParameter/ram:ID/text() = 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0'])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UN/CEFACT XML (SCRDM - CII
                    uncoupled)</name>
        <location>resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (CII)</name>
        <location>resources/cii/16b/xsl/EN16931-CII-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for CIUS XRechnung (CII)</name>
        <location>resources/xrechnung/3.0.2/xsl/XRechnung-CII-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <createReport>
      <resource>
        <name>Validation report for XRechnung</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
      <!-- custom level "information" for BR-CL-01 was removed as construction codes were added to Codelist 1001 with CEN 1.3.8 (see CEN issue https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/309) --> 
      <!-- overwrites CEN severity level "fatal" for codelist values of BT-130 "Invoiced quantity unit of measure code" and BT-150 "Item price base quantity unit of measure code" -->
      <customLevel level="warning">BR-CL-23</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-157 "Item standard identifier" scheme identifier -->
      <customLevel level="warning">BR-CL-21</customLevel>
      <!-- overwrites CEN severity level "warning" to enforce correct cardinality of BT-9 "Payment due date" and BT-20 "Payment terms" -->
      <customLevel level="error">CII-SR-452</customLevel>
      <!-- overwrites CEN severity level "warning" to replace BR-DE-18a in CII -->
      <customLevel level="error">CII-SR-453</customLevel>
       <!-- overwrites CEN severity level "warning" to enforce exactly one BG-30 within BG-25 -->
      <customLevel level="error">CII-SR-454</customLevel>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>
  
  <!-- XRechnung Extension CII -->
  <scenario>
    <name>EN16931 XRechnung Extension (CII)</name>
    <description>
      <p>Validates UN/CEFACT XML (SCRDM - CII uncoupled) version
        D16B</p>
      <p>Uses UN/CEFACT (SCRDM - CII uncoupled) version
        D16B XML Schema, Schematron rules from EN16931:2017,
        and XRechnung Schematron rules version 3.0.2 </p>
      <p>Download of CII uncoupled XML Schema on 2024-06-20 from
        http://www.unece.org/fileadmin/DAM/cefact/xml_schemas/D16B_SCRDM__Subset__CII.zip</p>
      <p>Download of CII Schematron rules on 2024-06-20 from
        https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-cii-1.3.12.zip </p>
      <p>Download of XRechnung Schematron rules on 2024-06-20 from
        https://github.com/itplr-kosit/xrechnung-schematron/releases/download/release-2.1.0/xrechnung-3.0.2-schematron-2.1.0.zip</p>
    </description>
    <!-- CII namespaces -->
    <namespace prefix="rsm"
      >urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100</namespace>
    <namespace prefix="ram"
      >urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>
    
    <match>exists(/rsm:CrossIndustryInvoice[rsm:ExchangedDocumentContext/ram:GuidelineSpecifiedDocumentContextParameter/ram:ID/text() = 'urn:cen.eu:en16931:2017#compliant#urn:xeinkauf.de:kosit:xrechnung_3.0#conformant#urn:xeinkauf.de:kosit:extension:xrechnung_3.0'])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UN/CEFACT XML (SCRDM - CII
          uncoupled)</name>
        <location>resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (CII)</name>
        <location>resources/cii/16b/xsl/EN16931-CII-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for CIUS XRechnung (CII)</name>
        <location>resources/xrechnung/3.0.2/xsl/XRechnung-CII-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    <createReport>
      <resource>
        <name>Validation report for XRechnung</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
      <!-- custom level "information" for BR-CL-01 was removed as construction codes were added to Codelist 1001 with CEN 1.3.8 (see CEN issue https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/309) --> 
      <!-- overwrites CEN severity level "fatal" for codelist values of BT-130 "Invoiced quantity unit of measure code" and BT-150 "Item price base quantity unit of measure code" -->
      <customLevel level="warning">BR-CL-23</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-157 "Item standard identifier" scheme identifier and to enable DIGA codes (BR-DEX-06) -->
      <customLevel level="information">BR-CL-21</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-30, BT-47, and BT-61 scheme identifiers to enable DIGA codes (BR-DEX-05) -->
      <customLevel level="information">BR-CL-11</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-29, BT-46, and BT-60 scheme identifiers to enable DIGA codes (BR-DEX-04) -->
      <customLevel level="information">BR-CL-10</customLevel>
      <!-- overwrites CEN severity level "fatal" for CEF EAS values of BT-34 and BT-49 scheme identifiers to enable DIGA codes (BR-DEX-07) -->
      <customLevel level="information">BR-CL-25</customLevel>
      <!-- overwrites CEN severity level "fatal" for ISO 6523 values of BT-71 scheme identifier to enable DIGA codes (BR-DEX-08) -->
      <customLevel level="information">BR-CL-26</customLevel>
      <!-- overwrites CEN severity level "warning" to enforce correct cardinality of BT-9 "Payment due date" and BT-20 "Payment terms" -->
      <customLevel level="error">CII-SR-452</customLevel>
      <!-- overwrites CEN severity level "warning" to replace BR-DE-18a in CII -->
      <customLevel level="error">CII-SR-453</customLevel>
      <!-- overwrites CEN severity level "warning" to enforce exactly one BG-30 within BG-25 -->
      <customLevel level="error">CII-SR-454</customLevel>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>


   <!-- Match for general CEN rules validation only: WITHOUT XRECHNUNG rules -->
  <scenario>
    <name>EN16931 (UBL Invoice)</name>
    <description>
      <p>Validates UBL Invoice in version 2.1</p>
      <p>Uses UBL Invoice 2.1 XML Schema,
                Schematron rules from EN16931:2017, and XRechnung
                3.0.2 </p>
      <p>Download of UBL XML Schema on 2024-06-20 from
                http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.zip</p>
      <p>Download of UBL Schematron rules on 2024-06-20 from
                https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-ubl-1.3.12.zip</p>
    </description>
    <!-- UBL Invoice namespaces -->
    <namespace prefix="cbc"
      >urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2</namespace>
    <namespace prefix="invoice"
      >urn:oasis:names:specification:ubl:schema:xsd:Invoice-2</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>

    <match>exists(/invoice:Invoice[ cbc:CustomizationID/text() = 'urn:cen.eu:en16931:2017' ])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UBL 2.1 Invoice</name>
        <location>resources/ubl/2.1/xsd/maindoc/UBL-Invoice-2.1.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (UBL)</name>
        <location>resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>

    <createReport>
      <resource>
        <name>Validation report for EN16931 (UBL Invoice)</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>

  <scenario>
    <name>EN16931 (UBL CreditNote)</name>
    <description>
      <p>Validates UBL CrediteNote version 2.1</p>
      <p>Uses UBL CreditNote 2.1 XML Schema, 
                Schematron rules from EN16931:2017, and XRechnung
                3.0.2 </p>
      <p>Download of UBL XML Schema on 2024-06-20 from
                http://docs.oasis-open.org/ubl/os-UBL-2.1/UBL-2.1.zip</p>
      <p>Download of UBL Schematron rules on 2024-06-20 from
                https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-ubl-1.3.12.zip</p>
     
    </description>
    <!-- UBL CrediteNote Namespaces -->
    <namespace prefix="cbc"
      >urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2</namespace>
    <namespace prefix="creditnote"
      >urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>

    <match>exists(/creditnote:CreditNote[cbc:CustomizationID/text() = 'urn:cen.eu:en16931:2017'])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UBL 2.1 CreditNote</name>
        <location>resources/ubl/2.1/xsd/maindoc/UBL-CreditNote-2.1.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (UBL)</name>
        <location>resources/ubl/2.1/xsl/EN16931-UBL-validation.xsl</location>
      </resource>
    </validateWithSchematron>
    
    <createReport>
      <resource>
        <name>Validation report for EN16931 (UBL CreditNote)</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>

  <scenario>
    <name>EN16931 (CII)</name>
    <description>
      <p>Validates UN/CEFACT XML (SCRDM - CII uncoupled) version
                D16B</p>
      <p>Uses UN/CEFACT (SCRDM - CII uncoupled) version
                D16B XML Schema, Schematron rules from EN16931:2017,
                and XRechnung Schematron rules version 3.0.2 </p>
      <p>Download of CII uncoupled XML Schema on 2024-06-20 from
                http://www.unece.org/fileadmin/DAM/cefact/xml_schemas/D16B_SCRDM__Subset__CII.zip</p>
      <p>Download of CII Schematron rules on 2024-06-20 from
                https://github.com/ConnectingEurope/eInvoicing-EN16931/releases/download/validation-1.3.12/en16931-cii-1.3.12.zip </p>
    </description>
    <!-- CII namespaces -->
    <namespace prefix="rsm"
      >urn:un:unece:uncefact:data:standard:CrossIndustryInvoice:100</namespace>
    <namespace prefix="ram"
      >urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:100</namespace>
    <!-- Namespace for acceptMatch XPATH within validator report XML -->
    <namespace prefix="rep">http://www.xoev.de/de/validator/varl/1</namespace>

    <match>exists(/rsm:CrossIndustryInvoice[ rsm:ExchangedDocumentContext/ram:GuidelineSpecifiedDocumentContextParameter/ram:ID/text() = 'urn:cen.eu:en16931:2017'])</match>
    <validateWithXmlSchema>
      <resource>
        <name>XML Schema for UN/CEFACT XML (SCRDM - CII
                    uncoupled)</name>
        <location>resources/cii/16b/xsd/CrossIndustryInvoice_100pD16B.xsd</location>
      </resource>
    </validateWithXmlSchema>
    <validateWithSchematron>
      <resource>
        <name>Schematron rules for EN16931 (CII)</name>
        <location>resources/cii/16b/xsl/EN16931-CII-validation.xsl</location>
      </resource>
    </validateWithSchematron>

    <createReport>
      <resource>
        <name>Validation report for EN16931 (CII)</name>
        <location>resources/xrechnung-report.xsl</location>
      </resource>
    </createReport>
    <acceptMatch>/rep:report/rep:assessment[1]/rep:accept[1]</acceptMatch>
  </scenario>

  <!-- In case none of the aboce scenarios matched/were applied -->
  <noScenarioReport>
    <resource>
      <name>Default Report</name>
      <location>resources/default-report.xsl</location>
    </resource>
  </noScenarioReport>
</scenarios>

**Comment by phax** [comment]
Ja okay. Ich habe mich an der Peppol Codeliste orientiert: https://docs.peppol.eu/edelivery/codelists/v8.9/Peppol%20Code%20Lists%20-%20Document%20types%20v8.9.html#237

**Comment by msccip** [comment]
Interessant. Wer erfindet denn solche Einträge ?

**Comment by phax** [comment]
Die KoSIT hat Sie extra beantragt :)

**Comment by phax** [comment]
Die Regel BR-CL-01 aus den EN16931 1.3.12 Regeln schaut wie folgt aus:
```xml
<assert id="BR-CL-01" flag="fatal" test="
(self::cbc:InvoiceTypeCode and ((not(contains(normalize-space(.), ' ')) and 
    contains(' 71 80 81 82 84 102 130 202 203 204 211 218 219 295 325 326 331 380 382 383 384 385 386 387 388 389 390 393 394 395 456 457 527 553 575 623 633 751 780 817 870 875 876 877 935 ', concat(' ', normalize-space(.), ' '))))) or 
(self::cbc:CreditNoteTypeCode and ((not(contains(normalize-space(.), ' ')) and 
    contains(' 81 83 261 262 296 308 381 396 420 458 532 ', concat(' ', normalize-space(.), ' ')))))
">[BR-CL-01]-The document type code MUST be coded by the invoice and credit note related code lists of UNTDID 1001.</assert>
```
Da ist also der `CreditNoteTypeCode`  mit dem Wert `381` drin.

@landrix  D.h. wenn eine UBL `CreditNote` korrekt verwendet wird, dann klappt das auch :)

**Comment by landrix** [comment]
@phax  ich habe es mit deinen CustomizationID's angepasst, nun klappt alles. Vielen Dank an alle.
