### ISSUE TITLE
Fehler im CII-Validator bei Validierung einer Rechnung mit mehreren Referenzen?

### ISSUE THREAD

**Issue by Naraielara** [itplr-kosit/validator-configuration-xrechnung#96]
Die Gruppe "Preceding Invoice Reference" ist in der Spezifikation von xRechnung 3.0.1 mit Kardinalität 0..* angegeben. Bei der Validierung bspw. der Testrechnung 01.18a-INVOICE_uncefact.xml ist dieses Element einmal vorhanden. Der Validator bestätigt, dass diese Rechnung valide ist. Füge ich das Element jedoch ein zweites Mal ein, so schlägt die Prüfung fehl (siehe Anhang für Testdatei sowie Validator-Ergebnis, Dateiendung von .xml auf .txt geändert, damit ich es hier hochladen darf). Liegt hier ein Fehler im CII-Validator vor?

Das entsprechende Element in einer UBL-Rechnung cac:BillingReference/cac:InvoiceDocumentReference ist bspw. in Testrechnung 04.03a-INVOICE_ubl.xml mehrfach vorhanden und wird dort auch akzeptiert.

[01.18a-INVOICE_uncefact.txt](https://github.com/user-attachments/files/16963126/01.18a-INVOICE_uncefact.txt)
[01.18a-INVOICE_uncefact-report.txt](https://github.com/user-attachments/files/16963127/01.18a-INVOICE_uncefact-report.txt)

**Comment by landrix** [comment]
Im CII-Format ist maximal ein Anhang erlaubt

https://portal3.gefeg.com/invoice/embed/indexplain?returnUrl=%2Finvoice%2Ftthome%2Findex%2F617afdc4-623f-44e0-a05b-5b878840e508%3Fpage%3D1%26useSelectedItemPosition%3Dtrue&url=https%3A%2F%2Fportal3.gefeg.com%2Fprojectdata%2Finvoice%2Fdeliverables%2Finstalled%2Fpublishingproject%2Fxrechnung%202.1.1%20-%20%28ab%2001.02.2022%29%2Fxrechnung_cii_v2.1.1_01.02.2022.scm%2Fhtml%2Fde%2Findex.htm&pt=HTML&bc=Invoice-Portal%20validation%20-%20GEFEG%20Admin%3A%3Ahttps%3A%2F%2Fportal3.gefeg.com%2Finvoice%2Fvalidation%2CDokumentation%3A%3A%2Finvoice%2Ftthome%2Findex%2F617afdc4-623f-44e0-a05b-5b878840e508

**Comment by Naraielara** [comment]
Ah, das hätte ich natürlich prüfen können. Dann hat sich das Issue bereits erledigt - vielen Dank!
