### ISSUE TITLE
Formulierung: Das geprüfte Dokument enthält 0 Fehler / 1 Warnungen. Es ist zu den formalen Vorgaben. Konformitätsprüfung: nicht konform

### ISSUE THREAD

**Issue by msccip** [itplr-kosit/validator-configuration-xrechnung#99]
Hallo,
die Formulierung ist etwas seltsam ...

![grafik](https://github.com/user-attachments/assets/60d9c50a-ecd9-4623-9d76-d672c9c37f3c)

**Comment by lkumai** [comment]
Da muss ich Ihnen zustimmen. Könnten Sie die Beispieldatei zur Verfügung stellen, damit wir den Fehler reproduzieren können?

**Comment by msccip** [comment]
[MOD01.01a-invoice_ubl.txt](https://github.com/user-attachments/files/17489879/MOD01.01a-invoice_ubl.txt)

Interessanterweise ist es im report-xml noch in Ordnung. Im dazugehörigen html steht es dann falsch.

xml:
<b>Konformitätsprüfung: </b>Das geprüfte Dokument enthält 0 Fehler / 1 Warnungen. Es ist <b>nicht konform</b> zu den formalen Vorgaben.

html:
<p class="important">Das geprüfte Dokument enthält 0 Fehler / 1 Warnungen. Es ist zu den formalen Vorgaben.
            <b>Konformitätsprüfung:</b>
            <b>nicht konform</b>
        </p>

**Comment by msccip** [comment]
den aktuellen 3.0.2. Mir ist es auch vorher nie aufgefallen...

**Comment by msccip** [comment]
Es läuft unter Windows. Der Validator wird über ein Batchfile aufgerufen. Die Beispielreports sind von einer anderen Rechnung, aber das Problem ist immer dasselbe: XML ok, HTML falsch. Ist es nicht so, dass das HTML aus dem XML erzeugt wird ?
[NEU 1-report.html.txt](https://github.com/user-attachments/files/17829833/NEU.1-report.html.txt)
[NEU 1-report.xml.txt](https://github.com/user-attachments/files/17829834/NEU.1-report.xml.txt)

**Comment by lkumai** [comment]
Können Sie Ihre Umgebung als ZIP-File zur Verfügung stellen, da wir das Problem nicht reproduzieren können?

**Comment by msccip** [comment]
Ich habe auch die aktuelle Konfiguration von vorgestern heruntergeladen. Es macht diesbzgl. keinen
[validator.rar.txt](https://github.com/user-attachments/files/17845126/validator.rar.txt)
 Unterschied.

**Comment by lkumai** [comment]
> Ich habe auch die aktuelle Konfiguration von vorgestern heruntergeladen. Es macht diesbzgl. keinen [validator.rar.txt](https://github.com/user-attachments/files/17845126/validator.rar.txt) Unterschied.

Vielen Dank! Können Sie auch die Batch-Dateien zur Verfügung stellen?

**Comment by lkumai** [comment]
> Das Problem tritt offenbar nur auf, wenn die Validierung über den Daemon Prozess erfolgt.

Ich habe Ihre Batch mit beiden Szenarien-Dateien getestet und kann bestätigen, dass dort die Ausgabe korrekt. Ich kann nur mutmaßen, dass bei Ihrem Daemon-Prozess es Probleme mit Sonderzeichen oder Steuerzeichen gibt, die dazu führen, dass die Ausgabe verrutscht.

**Comment by phax** [comment]
Ich hätte das so verstanden, dass der Fehler im Validator ist - nicht aber im Regelwerk der XRechnung. Dann wäre also https://github.com/itplr-kosit/validator das richtige Repo zur Fehlersuche. Oder ist das eine Fehlinterpretation von mir?

**Comment by lkumai** [comment]
> Ich hätte das so verstanden, dass der Fehler im Validator ist - nicht aber im Regelwerk der XRechnung. Dann wäre also https://github.com/itplr-kosit/validator das richtige Repo zur Fehlersuche. Oder ist das eine Fehlinterpretation von mir?

Die zugehörige Stelle, bei welchen der Fehler einzugrenzen ist, ist in Zeile 711 ff. in `src/default-report.xsl` in diesem Projekt. So gesehen ist das hier schon die richtige Stelle für die Frage.

Die benannte Stelle ist die folgende:

```xml
        <xsl:choose>
            <xsl:when test="$e + $w eq 0">
              <xsl:text>weder Fehler noch Warnungen. Es ist konform zu den formalen Vorgaben.</xsl:text>
            </xsl:when>
            <xsl:otherwise>
              <xsl:value-of
                select="concat($e, ' Fehler / ', $w, ' Warnungen. Es ist ')" />
              <b>nicht konform</b>
              <xsl:text> zu den formalen Vorgaben.</xsl:text>
            </xsl:otherwise>
          </xsl:choose>
```

Es scheint so, dass irgendwie die Reihenfolge der einzelnen Elemente der Meldung durcheinander gekommen ist. Allerdings ist der Fehler weder im Ant-Skript noch mit dem mitgegebenen Batch-File reproduzierbar, weswegen ich vermute, dass das Problem irgendwie im Daemon-Prozess liegen müsste (vielleicht ein Bug im XSLT-Prozessor).

**Comment by phax** [comment]
Ah, es sollte also `($e + $w) eq 0` statt `$e + $w eq 0` sein.
Daher die Frage: welcher XSLT-Prozessort (Saxon oder Xalan) in welcher Version zum Einsatz kommt?

**Comment by lkumai** [comment]
@msccip Welchen Prozessor in welcher Version nutzen Sie in dem Daemon-Prozess?

**Comment by msccip** [comment]
Hallo,
ich war leider von einer falschen Voraussetzung ausgegangen. Im Falle der Validierung per Daemon wird - im Gegensatz zur  Vorgehensweise ohne Daemon - von dem Prozess ja lediglich der XML Part zurückgeliefert. Dieser ist, wie beschrieben, ok. Aus dem XML wird unserseits per XML Tool der HTML Part ausgelesen und als Datei gespeichert. Hierbei passiert der Fehler. Dieses Tool bringt an der besagten Stelle die Reihenfolge durcheinander. Warum offensichtlich nur an dieser einen Stelle - wer weiß. Ich benutze nun ein anderes Tool und damit ist dann auch das HTML ok. Tut mir leid für die Verwirrung und nochmals Danke.
